name: Build

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rye 
        uses: sksat/setup-rye@v0.23.1
    
      - name: Rye sync        
        run: rye sync

      - name: Build
        run: rye build

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          overwrite: true

  release:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/eyesy-api-stubs
    # tag が push されたときだけ実行
    if: startsWith(github.ref, 'refs/tags/')
    needs: [linux]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
